# Generated by Django 3.0.3 on 2020-12-15 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('pk_bint_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('vchr_name', models.CharField(max_length=120)),
                ('vchr_address', models.CharField(max_length=200)),
                ('dat_dob', models.DateField()),
                ('vchr_gender', models.CharField(max_length=100)),
                ('vchr_email', models.EmailField(max_length=254, unique=True)),
                ('vchr_languages', models.CharField(max_length=200)),
            ],
        ),
    ]
